### ISSUE TITLE
local storage doesn't work on testdroid

### ISSUE THREAD

**Issue by abdulkhaliquem9** [bitbar/test-samples#166]
Hi,
I have tested my react-native project which has e2e test cases written using detox e2e library. My test case fails at testdroid when I am trying to save the data locally and stops all subsequent test cases from being tested. I have tested the app locally and it got passed, but, It is unable to get passed on the testdroid. 
**Is bitbar.com team supporting local storage/device storage on testdroid.**

**Comment by marverix** [comment]
Correct me if I'm wrong, but it's more like it depends on device itself and framework. We do not limit the usage of any API provided by the framework, SDK, or whatever. So for me it sounds like maybe device that you have picked was too old for this react-native app? Closing for now. Please feel free to reopen this issue if you feel that it's still valid.
