### ISSUE TITLE
How to run appium-client script 

### ISSUE THREAD

**Issue by yajuntang** [bitbar/test-samples#202]
Hello, I have finished my script by referring to bitbar_android.py and run-test.py. When I run Python my run-test.py in terminal of pycharm, the following error appears
```
   raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='appium.bitbar.com', port=443): Max retries exceeded with url: /wd/hub:443/wd/hub/session (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

```
I don't know how to run my script on bitbar. I can't find any useful information in bitbar's documents. It seems very complicated. I'm not sure if I need to upload the script to bitbar

**Comment by LukaszSiudakiewicz** [comment]
All necessary instruction of how to run both Client and Cloud side Appium can be found at Bitbar's docs pages https://support.smartbear.com/bitbar/docs/testing-with-bitbar/automated-testing/appium/index.html . For Client side Appium only thing that need to be uploaded to Bitbar Cloud before starting the execution is test application  (https://support.smartbear.com/bitbar/docs/testing-with-bitbar/automated-testing/appium/running-client-side-appium-tests.html#upload-your-app-to-cloud ). For more information about Appium execution please use community or support ( https://support.smartbear.com/bitbar/ ).

As for the error massage; Please check if You are not using problematic version of python ( https://github.com/urllib3/urllib3/issues/1682#issuecomment-533311857 ) also if You are using 'requests' ( https://pypi.org/project/requests/ ) like in our example then check if it's up to date and update if it's not.

**Comment by yajuntang** [comment]
Thank you very much for your reply. I have worked normally according to your reply
