### ISSUE TITLE
When trying to execute test on device on which the user doe's not have a subscription for, the test fails without proper message

### ISSUE THREAD

**Issue by itaiag** [bitbar/test-samples#25]
When trying to execute test on device on which the user doe's not have a subscription for, the test fails due to null pointer exception. 
The user needs to debug the code in order to understand that the failure reason is _"Resource is in invalid state: Failed to submit test run! No active subscription plan to run tests on selected devices."_

**Comment by marverix** [comment]
Issue is probably depracated. Closing for now. Please feel free to re-open it, if you feel that it's still valid.
