### ISSUE TITLE
Port device_finder.py to Ruby

### ISSUE THREAD

**Issue by bootstraponline** [bitbar/test-samples#48]
It'd be nice to have a `device_finder.rb` based on the same [python class](https://github.com/bitbar/testdroid-samples/blob/03fc043ba98235b9ea46a0ab8646f3b20dd1960e/appium/sample-scripts/python/device_finder.py). My testdroid tests often error with the all `devices are busy at the moment. Please try again later`

I'd rather have them run on an available device than not run at all.

**Comment by villeveikkohelppi** [comment]
That's great idea, thanks! We'll take a look at it.

**Comment by bootstraponline** [comment]
@villeveikkohelppi https://github.com/bootstraponline/testdroid_device_finder

**Comment by marverix** [comment]
Issue is probably depracated. Closing for now. Please feel free to re-open it, if you feel that it's still valid.
