### ISSUE TITLE
android Injecting to another application requires INJECT_EVENTS

### ISSUE THREAD

**Issue by ShraddhaGadesha** [bitbar/test-samples#98]
Failed to perform gesture. java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (RuntimeError) I am getting error when i write Then I press view with id "button1" in my test case in android 5.1 and 4.3

**Comment by marverix** [comment]
The issue is probably deprecated. Closing for now. Please feel free to re-open it, if you feel that it's still valid.
